init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

skip_tags: true

environment:
  matrix:
    - nodejs_version: '1'
    - nodejs_version: '0'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install from2-string tape vinyl --no-bin-links

build: off

test_script:
  - ps: 'node test.js #PowerShell'
  - node test.js

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache -> package.json'
