shallow_clone: true
version: '{build}'
skip_tags: true
install:
  - ps: Install-Product node 4
  - npm install
build: off
test_script: node --strong_mode test.js
cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache -> package.json'
